In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os, time

In [33]:
pd.set_option('display.max_columns', 300)

In [35]:
person_seoul = pd.read_csv("./data/자치구단위 서울 생활인구 일별 집계표.csv",encoding='euc-kr')

In [36]:
person_seoul = person_seoul[person_seoul['기준일ID']==20200905].iloc[1:].copy()

## 서울시의 시군구별-표준산업분류별 비율

In [37]:
# df = seoul_data.groupby(['표준산업분류명','시군구명']).count()[['상가업소번호']].copy()
# df['ind'] = df.index
# df['표준산업분류명'] = df['ind'].apply(lambda x: x[0])
# df['시군구명'] = df['ind'].apply(lambda x: x[1])
# df = df.drop(columns=['ind']).copy()
# df.index = range(len(df))
# df.columns = ['상가_개수','표준산업분류명','시군구명']
# df = df[['표준산업분류명','시군구명','상가_개수']].copy()

# gu_list = person['시군구명'].unique().tolist()
# df['인구수'] = 0
# for i in gu_list:
#     df.loc[df['시군구명']==i,'인구수'] = person.loc[person['시군구명']==i,'총생활인구수'].iloc[0]
    
# work = df['표준산업분류명'].unique().tolist()
# df['비율'] = df['인구수']/df['상가_개수']
# ratio_mean = df.groupby("표준산업분류명").mean()[['비율']].copy()
# ratio_mean['표준산업분류명'] = ratio_mean.index
# ratio_mean.index = range(len(ratio_mean))

# df['평균비율'] = 0
# for i in work:
#     df.loc[df['표준산업분류명']==i,'평균비율'] = ratio_mean.loc[ratio_mean['표준산업분류명']==i,'비율'].iloc[0]

# df['tf'] = df['비율']<df['평균비율']
# check = df[df['tf']==True].copy()
# check.groupby('시군구명').count().sort_values(['상가_개수'])[['상가_개수']]
# check.groupby(["표준산업분류명","시군구명"]).mean()[['비율','평균비율']]

In [38]:
df = seoul_data.groupby(['상권업종소분류명','시군구명']).count()[['상가업소번호']].copy()
df['ind'] = df.index
df['상권업종소분류명'] = df['ind'].apply(lambda x: x[0])
df['시군구명'] = df['ind'].apply(lambda x: x[1])
df = df.drop(columns=['ind']).copy()
df.index = range(len(df))
df.columns = ['상가_개수','상권업종소분류명','시군구명']
df = df[['상권업종소분류명','시군구명','상가_개수']].copy()
df

   상권업종소분류명 시군구명  상가_개수
0      수퍼마켓  강남구    331
1      수퍼마켓  강동구    157
2      수퍼마켓  강북구    133
3      수퍼마켓  강서구    191
4      수퍼마켓  관악구    232
..      ...  ...    ...
95      할인점  용산구     20
96      할인점  은평구     17
97      할인점  종로구     17
98      할인점   중구     24
99      할인점  중랑구     20

[100 rows x 3 columns]

In [39]:
gu_list = person_seoul['시군구명'].unique().tolist()
df['인구수'] = 0
for i in gu_list:
    df.loc[df['시군구명']==i,'인구수'] = person_seoul.loc[person_seoul['시군구명']==i,'총생활인구수'].iloc[0]

In [40]:
df

   상권업종소분류명 시군구명  상가_개수          인구수
0      수퍼마켓  강남구    331  712677.7667
1      수퍼마켓  강동구    157  519012.2972
2      수퍼마켓  강북구    133  315295.7158
3      수퍼마켓  강서구    191  551978.5028
4      수퍼마켓  관악구    232  524484.8413
..      ...  ...    ...          ...
95      할인점  용산구     20  285430.4140
96      할인점  은평구     17  474505.7563
97      할인점  종로구     17  246753.1785
98      할인점   중구     24  210175.8843
99      할인점  중랑구     20  377161.9383

[100 rows x 4 columns]

In [41]:
work = df['상권업종소분류명'].unique().tolist()
df['비율'] = df['인구수']/df['상가_개수']
ratio_mean = df.groupby("상권업종소분류명").mean()[['비율']].copy()
ratio_mean['상권업종소분류명'] = ratio_mean.index
ratio_mean.index = range(len(ratio_mean))

In [42]:
df['평균비율'] = 0
for i in work:
    df.loc[df['상권업종소분류명']==i,'평균비율'] = ratio_mean.loc[ratio_mean['상권업종소분류명']==i,'비율'].iloc[0]

In [43]:
df

   상권업종소분류명 시군구명  상가_개수          인구수            비율          평균비율
0      수퍼마켓  강남구    331  712677.7667   2153.105035   2423.317459
1      수퍼마켓  강동구    157  519012.2972   3305.810810   2423.317459
2      수퍼마켓  강북구    133  315295.7158   2370.644480   2423.317459
3      수퍼마켓  강서구    191  551978.5028   2889.939805   2423.317459
4      수퍼마켓  관악구    232  524484.8413   2260.710523   2423.317459
..      ...  ...    ...          ...           ...           ...
95      할인점  용산구     20  285430.4140  14271.520700  18776.081215
96      할인점  은평구     17  474505.7563  27912.103312  18776.081215
97      할인점  종로구     17  246753.1785  14514.892853  18776.081215
98      할인점   중구     24  210175.8843   8757.328513  18776.081215
99      할인점  중랑구     20  377161.9383  18858.096915  18776.081215

[100 rows x 6 columns]

In [44]:
df['tf'] = df['비율']<df['평균비율']

In [45]:
check = df[df['tf']==True].copy()

In [46]:
check.groupby('시군구명').count().sort_values(['상가_개수'])[['상가_개수']]

      상가_개수
시군구명
서대문구      1
은평구       1
양천구       1
관악구       1
마포구       1
송파구       2
성동구       2
중랑구       2
구로구       2
강서구       2
동대문구      3
금천구       3
서초구       3
성북구       3
광진구       3
강북구       3
도봉구       3
강남구       3
중구        4
영등포구      4
용산구       4
종로구       4

In [47]:
check.groupby(["상권업종소분류명","시군구명"]).mean()[['비율','평균비율']]

                         비율          평균비율
상권업종소분류명 시군구명
수퍼마켓     강남구    2153.105035   2423.317459
         강북구    2370.644480   2423.317459
         관악구    2260.710523   2423.317459
         광진구    1729.688207   2423.317459
         구로구    2014.886615   2423.317459
         금천구    1318.525612   2423.317459
         도봉구    2033.395809   2423.317459
         동대문구   1636.040984   2423.317459
         성북구    2108.286952   2423.317459
         영등포구   2030.643510   2423.317459
         용산구    1877.831671   2423.317459
         종로구    2263.790628   2423.317459
         중구     1893.476435   2423.317459
         중랑구    1714.372447   2423.317459
종합소매     강북구    2352.953103   7108.745609
         도봉구    6700.963461   7108.745609
         동대문구   2126.853279   7108.745609
         서대문구   5308.596130   7108.745609
         서초구     512.506319   7108.745609
         성동구    6760.909053   7108.745609
         성북구    5126.970543   7108.745609
         송파구     881.568747   7108.745609
         영등포구    878.116113   7108.745609
         용산구    2083.433679   7108.745609
         은평구    4994.797435   7108.745609
         종로구     145.835212   7108.745609
         중구       97.484176   7108.745609
         중랑구    5714.574823   7108.745609
편의점      강남구     841.414128   1252.422725
         강서구    1171.928881   1252.422725
         광진구     868.637279   1252.422725
         금천구     959.437786   1252.422725
         동대문구   1109.662581   1252.422725
         마포구    1106.294248   1252.422725
         서초구    1208.473329   1252.422725
         성북구    1130.760421   1252.422725
         영등포구    990.989425   1252.422725
         용산구    1077.095902   1252.422725
         종로구     859.767172   1252.422725
         중구      578.996926   1252.422725
할인점      강남구   13705.341667  18776.081215
         강북구   15014.081705  18776.081215
         강서구   16234.661847  18776.081215
         광진구   17221.678235  18776.081215
         구로구   16441.474780  18776.081215
         금천구   10736.565695  18776.081215
         도봉구   12819.234448  18776.081215
         서초구   16879.643597  18776.081215
         성동구    9577.954492  18776.081215
         송파구   16514.721191  18776.081215
         양천구   16815.263333  18776.081215
         영등포구  11970.109113  18776.081215
         용산구   14271.520700  18776.081215
         종로구   14514.892853  18776.081215
         중구     8757.328513  18776.081215

In [49]:
df.to_csv('people_seoul.csv',encoding='euc-kr')