# 데이터 처리 환경 설정

In [265]:
import warnings
warnings.filterwarnings(action='ignore')
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import collections
import datetime
import time


from matplotlib import font_manager, rc
from matplotlib import style
style.use('ggplot')
%matplotlib inline

font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

from IPython.display import set_matplotlib_formats
set_matplotlib_formats("retina")

pd.set_option('display.max_rows', 220)
pd.set_option('display.max_columns', 10)

## 데이터 불러오기

In [272]:
data20=pd.read_csv("./data/2020동별 유동인구.csv", encoding='cp949')
data19=pd.read_csv("./data/2019동별 유동인구.csv", encoding='utf-8')

## 읍면동 list로 뽑기

In [273]:
data_dong_list=[]
for i in data20['읍면동'].unique():
    data_dong_list.append(i)

## 2019년 데이터 전처리

In [274]:
for i in range(6,13):
    globals()['df{}'.format(i)]=data19[data19['월']==i]
    
data19=pd.concat([df8,df9,df10,df11,df12], axis=0)
data19=data19.reset_index()

data19['평균 유동인구']=[pd.to_numeric(data19['평균 유동인구'][i].replace(',','').replace('명','')) for i in range(len(data19['평균 유동인구']))]

data_move=[]
for i in range(8,13):
    for j in data_dong_list:
        data_move.append(data19[(data19['읍면동']==j)&(data19['월']==i)]['평균 유동인구'].sum())
        
data19=data19[data19['요일']=='일']
data19=data19.reset_index()
data19['총 유동인구']=0
for i in range(len(data_move)):
    data19['총 유동인구'][i]=data_move[i]
    
data19=data19[(data19['요일']=='일')]
data19=data19[['구군','년','월','읍면동','총 유동인구']]
data19

      구군     년   월  읍면동  총 유동인구
0     중구  2019   8  중앙동  124902
1     중구  2019   8  동광동   29581
2     중구  2019   8  대청동   50901
3     중구  2019   8  보수동   54940
4     중구  2019   8  부평동   68784
..   ...   ...  ..  ...     ...
995  사상구  2019  12  엄궁동  211134
996  기장군  2019  12  기장읍  423219
997  기장군  2019  12  장안읍  103656
998  기장군  2019  12  일광면   86151
999  기장군  2019  12  철마면   42571

[1000 rows x 5 columns]

## 2020년 data 전처리

In [275]:
data20['주중/주말 유동인구']=[pd.to_numeric(data20['주중/주말 유동인구'][i].replace(',','')) for i in range(len(data20['주중/주말 유동인구']))]
data_move=[]
for i in range(1,8):
    for j in data_dong_list:
        data_move.append(data20[(data20['읍면동']==j)&(data20['월']==i)]['주중/주말 유동인구'].sum())
        
data20['총 유동인구']=0
for i in range(len(data_move)):
    data20['총 유동인구'][i]=data_move[i]
    
data20=data20[data20['요일']=='일']
data20=data20[['구군','년','월','읍면동','총 유동인구']]
data20

       구군     년  월  읍면동  총 유동인구
0      중구  2020  1  중앙동  108457
1      중구  2020  1  동광동   27870
2      중구  2020  1  대청동   55568
3      중구  2020  1  보수동   60563
4      중구  2020  1  부평동   66109
...   ...   ... ..  ...     ...
1395  기장군  2020  6  철마면  191013
1396  기장군  2020  7  기장읍  427352
1397  기장군  2020  7  장안읍  105837
1398  기장군  2020  7  일광면   96131
1399  기장군  2020  7  철마면   66538

[1400 rows x 5 columns]

In [276]:
data=pd.concat([data19, data20], axis=0)
data

       구군     년  월  읍면동  총 유동인구
0      중구  2019  8  중앙동  124902
1      중구  2019  8  동광동   29581
2      중구  2019  8  대청동   50901
3      중구  2019  8  보수동   54940
4      중구  2019  8  부평동   68784
...   ...   ... ..  ...     ...
1395  기장군  2020  6  철마면  191013
1396  기장군  2020  7  기장읍  427352
1397  기장군  2020  7  장안읍  105837
1398  기장군  2020  7  일광면   96131
1399  기장군  2020  7  철마면   66538

[2400 rows x 5 columns]

In [277]:
data.to_csv('부산_읍면동_월별_총 유동인구.csv', encoding='euc-kr')